apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-notification
spec:
  replicas: 1
  template:
    metadata:
      name: service-notification
      labels:
        app: service-notification
    spec:
      containers:
        - name: service-notification
          image: densold/micro_project-service-notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: notification-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: service-notification
