server:
  port: 8081

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:9411/api/v2/spans

spring:
  application:
    name: service-customer
    version: 0.0.1-SNAPSHOT
  banner:
    location: application-banner.txt
  config:
    import: optional:file:service-customer/.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  rabbitmq:
    addresses: ${RABBITMQ_HOST}:5672

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka
    fetch-registry: true
    register-with-eureka: true