server:
  port: 8081

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

spring:
  application:
    name: service-customer
    version: 0.0.1-SNAPSHOT
  banner:
    location: application-banner.txt
  config:
    import: optional:file:service-customer/.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true