server:
  port: 8083

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

spring:
  application:
    name: service-notification
    version: 0.0.1-SNAPSHOT
  banner:
    location: application-banner.txt
  config:
    import: optional:file:service-notification/.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#    show-sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key