server:
  port: 8080

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

spring:
  application:
    name: service-gateway
    version: 0.0.1-SNAPSHOT
  banner:
    location: application-banner.txt

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true