server:
  port: 8080

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

spring:
  application:
    name: service-gateway
    version: 0.0.1-SNAPSHOT
  config:
    import: optional:file:service-gateway/.env[.properties]
  banner:
    location: application-banner.txt
  cloud:
    gateway:
      routes:
        - id: service-customer
          uri: lb://SERVICE-CUSTOMER
          predicates:
            - Path=/api/v1/customer/**
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka
    fetch-registry: true
    register-with-eureka: true