server:
  port: 8761

spring:
  application:
    name: eureka-server
    version: 0.0.1-SNAPSHOT
  banner:
    location: application-banner.txt

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF